services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: personal-finance-accounting-system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-gateway:
    build: ./services/api-gateway
    depends_on:
      - rabbitmq
      - postgres
    environment:
      RABBITMQ_URL: amqp://rabbitmq
      DATABASE_URL: postgres://admin:password@postgres:5432/personal-finance-accounting-system
    ports:
      - "3000:3000"
    volumes:
      - ./services/api-gateway:/app
    command: ["npm", "run", "start"]

volumes:
  postgres_data:

